name: worlds_away
description: Chat App With CA and BLoC.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  google_sign_in: ^6.1.4
  get_it: ^7.6.0
  equatable: ^2.0.5
  shared_preferences: ^2.2.0
  cached_network_image: ^3.2.3
  intl: ^0.18.1
  rxdart: ^0.27.7
  firebase_messaging: ^14.6.7
  retrofit: ^4.0.1
  dio: ^5.3.2
  firebase_storage: ^11.2.6
  file_picker: ^5.5.0
  fluttertoast: ^8.2.2
  flutter_background_service: ^5.0.1
  flutter_slidable: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: ^7.0.8
  build_runner: ^2.4.6


flutter:

  uses-material-design: true

  assets:
    - assets/images/worlds_away_logo.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
